# Generated by Django 3.0.5 on 2023-07-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_facility_alter_doctor_department_paramedic_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='roomID',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
